version: '3.8'

services:  
  locus_db:
    container_name: locus_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "locus_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "miguel"
    ports:
      - '5432:5432'      
    networks:
      - backend

volumes:
  pgdata:
