version: '3.8'

services:
  locus_api:
    container_name: locus_api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    depends_on:
      - locus_db
    networks:
      - backend

  locus_db:
    container_name: locus_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "locus_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "miguel"
    ports:
      - '5433:5432'      
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: