version: '3.8'

services:
  locus_api2:
    container_name: locus_api2
    build:
      context: .
      dockerfile: ./Dockerfile2
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    depends_on:
      - locus_db2
    networks:
      - backend

  locus_db2:
    container_name: locus_db2
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "locus_db2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "miguel"
    ports:
      - '5433:5432'      
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: