version: '3.8'

services:
  locus_api:
    container_name: locus_api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    # command: npm run start
    # env_file:
    #   - ./src/main/resources/application.properties
    depends_on:
      - locus_db
  locus_db:
    container_name: locus_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "locus_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "miguel"
    # volumes:
      # - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  pgdata:
